### ISSUE TITLE
Add verification rules to community

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#145]

**Comment by luizalbsilva** [comment]
Pensei em algo asim:

![image](https://cloud.githubusercontent.com/assets/297639/22524415/48568fce-e8aa-11e6-8f3f-05db97ed2bfb.png)

**Comment by lpirola** [comment]
Maybe we could separate mailchimp and pagarme with different status? If I only publish a mobilization with form_entry widget, maybe pagarme config is extra step I don't need right now @luizalbsilva

**Comment by luizalbsilva** [comment]
Yes, we may do it. 

I was figuring out in other thing... maybe create 2 other routes, to create/modify access keys on external services. Each of those endpoits would not only save the keys and update the state(status), but TEST if that key is valid. What do you guys think? @devton @lpirola

**Comment by lpirola** [comment]
@luizalbsilva I guesse it's better to have only one endpoint which will check and set new statuses. Multiple requests slowdow frontend performance.
