### ISSUE TITLE
FactoryGirl

### ISSUE THREAD

**Issue by luizalbsilva** [nossas/bonde-server#159]
Nowadays (v.0.2.x) we're using Machinist 2, but this framework has no maintenance for the last 4 years (in fact, almost 5, since the last real modification was for update on dependencies, on mar 2nd, 2013).

Well, I'm thinking on using another one (maybe factory girl), but not replacing machinist at one, but start using on new implementations, and replacing code with time.

**Comment by lpirola** [comment]
Great @luizalbsilva, if @devton agree too we can move on!

**Comment by devton** [comment]
agree ;) factory girl is maintained by thoughtbot

**Comment by lpirola** [comment]
Time to PR! ⌚️
