### ISSUE TITLE
Add rewrite rules in old project paneladepressao

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#160]
We need to add some rewrite rules when old campaigns from "Panela de Pressão" will be redirect to new campaign at new URL.

I tried redirect with nginx but this project use unicorn to serve app. After some research, I found a library to redirect some urls: https://github.com/jtrupiano/rack-rewrite

Is this the right way to do? @luizalbsilva @devton  

Link to project: https://github.com/nossas/panela-de-pressao

**Comment by devton** [comment]
@lpirola https://github.com/nossas/panela-de-pressao/pull/50
