### ISSUE TITLE
Better error handling when logging mailchimp activities

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#170]

**Comment by luizalbsilva** [comment]
We'll mailchimp returns the same error kind if you try to subscribe an activist that a) have an invalid email; b) have an email that HE thinks that is invalid (like one from facebook we saw earlier c) One that someone had complained our emails as spammy d) some other error in the server

**Comment by luizalbsilva** [comment]
PR #211 - https://github.com/nossas/bonde-server/pull/211
