### ISSUE TITLE
Creation domain and subdomains management routes

### ISSUE THREAD

**Issue by luizalbsilva** [nossas/bonde-server#178]

**Comment by luizalbsilva** [comment]
Since we're gonna be working with amazon's route 53, I was thinking on 2 entities (models), reflecting the same way amazon works:

1) Hosted Zones
	endpoint: /communities/:community_id/dns_hosted_zones
	Fields: domain_name, comment, hosted_zone_id


2) recordset
	endpoint: /communities/:community_id/dns_hosted_zones/:hosted_zone_id/recordset
	fields:
	  - name: Domain name for the recordset. Can be up to 63 chars ans total length can be up to 255 chars
	  - type (type of the value): 
		* A : IPv4 address - Specify the IP used 
		* CNAME: Canonical Name - Value receive an URL wich name will respond to
		* MX: Mail Exchange - Value will receive a priority number and a domain name, multiple values in multiple lines
		* AAAA: IPv6 address
		* TXT: Text record. Multiple values in multiple lines.
		* PTR: Pointer Value will have a domainame to be returned
		* SRV: Service Locator
		* SPF: Sender policy framework
		* NAPRT Name Authority Pointer
		* NS - Name Server
		* SOA - Start of Authority
		* SOA - Start
	  - value
	  - ttl: time to live - seconds

**Comment by lpirola** [comment]
I agree @luizalbsilva, we could also make space for live an integration to Route 53 and an arrangement to server infra.
