### ISSUE TITLE
Check size from subdomains and domains

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#183]
Route 53 will not accept urls like these: 336-vereadores-queremos-um-conselho-municipal-dos-direitos-da-mulher-em-ouro-preto.reboo.org

**Comment by luizalbsilva** [comment]
I think there is a limit of 63 chars for the name of the subdomain, and 255 chars for the whole uri.

**Comment by lpirola** [comment]
Great, I guess that limit must be forced into our forms and API.

**Comment by luizalbsilva** [comment]
Isn't this related to PR #120?

**Comment by lpirola** [comment]
@luizalbsilva yes, it's related but my comment was about force this validation in register host_zone and subdomains.

**Comment by luizalbsilva** [comment]
Found problem related to issue #248, soon returning to it. We'll need to restore the staging databses to test this stuff

**Comment by luizalbsilva** [comment]
PR https://github.com/nossas/bonde-server/pull/254
