### ISSUE TITLE
Return widget_attributes in `[POST] /mobilizations/{mobilization_id}/blocks`

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-server#186]
Hello,

The payload for endpoint `[POST] /mobilizations/{mobilization_id}/blocks` receive `widget_attributes` attribute, but did not return that attribute in response data.

For change my state corretly, i need this attributes on response with widget.id filled.

Can you help me?

**Comment by luizalbsilva** [comment]
Is something like this you're looking for?

{
    "id": 265,
    "mobilization_id": 56,
    "created_at": "2015-11-16T16:32:11.186-02:00",
    "updated_at": "2015-11-16T16:32:11.186-02:00",
    "bg_class": "bg-1",
    "position": 1,
    "hidden": null,
    "bg_image": null,
    "name": null,
    "menu_hidden": null,
    "widgets_attributes": [
      {
        "id": 4,
        "block_id": 2165,
        "kind": "content",
        "settings": {
          "content": "<iframe src=\"https://www.youtube.com/embed/asdwqqwo\" width=\"420\" height=\"315\" frameborder=\"0\"></iframe>&nbsp;Texto sobre o vídeo"
        },
        "sm_size": 12,
        "md_size": 12,
        "lg_size": 12,
        "form_entries_count": 0,
        "donations_count": 0,
        "created_at": "2015-11-16T16:32:11.193-02:00",
        "updated_at": "2015-11-16T18:51:28.822-02:00",
        "action_community": false,
        "action_opportunity": false,
        "exported_at": null,
        "match_list": [],
        "count": 0
      }
    ]
  }

**Comment by igr-santos** [comment]
That is it, thank you!

**Comment by luizalbsilva** [comment]
Use this branch for testing , when we finish it we will put it on next release

**Comment by igr-santos** [comment]
I finished test. This resource can go to next version.

Thanks
