### ISSUE TITLE
 Create responsive html to e-mail notifications

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#207]
Ref: https://app.zeplin.io/project.html#pid=55d1d57e14a5317a0e909551&dashboard&tags=email-templates

**Comment by lpirola** [comment]
https://github.com/nossas/bonde-server/blob/master/app/views/layouts/mailer.html.erb

**Comment by gabrielrtakeda** [comment]
I think it is not this file that I have to change...
https://github.com/nossas/bonde-server/blob/master/app/views/layouts/mailer.html.erb

Does this file is not a global email template?
