### ISSUE TITLE
Add default entries when domain is rooted to bonde

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#213]

**Comment by lpirola** [comment]
54.94.197.80 ip de cache

**Comment by luizalbsilva** [comment]
Question: An preexistent entry will we overriden or will be ignored?

**Comment by luizalbsilva** [comment]
Ajustar variável de ambiente AWS_ROUTE_IP com IP do servidor (ou do cache)

**Comment by luizalbsilva** [comment]
Released: v. 0.5.2
