### ISSUE TITLE
Dynamic manager automatic tags based on widget actions(donation,form_entries,pressure)

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#214]

**Comment by luizalbsilva** [comment]
In an earlier talk, we decided that the name was going to be something like: widget-type:mobilization-name-without-spaces. But, during the implementation of some specs, I've found a problem: the acts-as-taggable-on gem already chenges the spaces to an '-', what is great... BUT not onl spaces, but many more chars, like the ':' :(
I'm searching in the documentation for some information about the characteres that are avaliable to us, and if there is some kind of configuration about this  issue.

**Comment by luizalbsilva** [comment]
Examples of queries you've asked for:
	All activists that had signed a form-entry in community 37:
```
		select act.*
			from activists act
			inner join activist_tags atg
				 on (atg.activist_id =  act.id)
				and (atg.community_id = 37)
			inner join taggings tgg 
				 on ( tgg.taggable_id = atg.id )
				and ( tgg.taggable_type = 'ActivistTag' )
			inner join tags tag
				 on ( tgg.tag_id = tag.id )
				and ( tag.name like 'form_%' )
```

	All activists that have signed the pressure form 'pressure_n-o-tire-meu-cobertor:
```
		select act.*, tag.name
			from activists act
			inner join activist_tags atg
				 on (atg.activist_id =  act.id)
				and (atg.community_id = 9)
			inner join taggings tgg 
				 on ( tgg.taggable_id = atg.id )
				and ( tgg.taggable_type = 'ActivistTag' )
			inner join tags tag
				 on ( tgg.tag_id = tag.id )
				and ( tag.name = 'pressure_n-o-tire-meu-cobertor' )

```
	Observations:
 		* table tag: Where all tags are.
		* table taggings: Table that connects a tag (throught tag_id) a an object (taggble_type holds the class name, and taggagle_id it's id)
		* Table activist_tags: holds the many tags from an activist / community (activist_id/community_id)

**Comment by luizalbsilva** [comment]
PR https://github.com/nossas/bonde-server/pull/236

**Comment by lpirola** [comment]
@luizalbsilva We have some auto tag activists and mobilization?

**Comment by lpirola** [comment]
@igr-santos @gabrielrtakeda this issue show a SQL example on how to search tags by type and by text name.
