### ISSUE TITLE
Check if DNS was registered in service used by customer

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-server#224]
I need a endpoint in API to check if customer registered the server names received by Amazon (`[POST] /communities/:community_id/dns_hosted_zones`) on service of domain him, also should store a flag in database to response of `GET /communities/:community_id/dns_hosted_zones`.

Thank's!

**Comment by luizalbsilva** [comment]
I'm just returning true or false. If you need somwthing else, please contact me. To test while we don't PR, you may get the code on 'feature-check_status_dns_record' branch

Endpoint:
GET      /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/check

**Comment by lpirola** [comment]
@luizalbsilva Maybe we could add this feature to develop, if you finished. Its easy to client team always checkout the develop version.

**Comment by luizalbsilva** [comment]
If the response is ok to @igr-santos (just true/false), I can merge right now -- the branch is up-to-date with develop

**Comment by lpirola** [comment]
Maybe a valid JSON? If we follow something related to this documentation. 

http://jsonapi.org/format/#error-objects

**Comment by lpirola** [comment]
We could use something like that:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "invalid query"
}
```

https://github.com/hapijs/boom

**Comment by luizalbsilva** [comment]
Wait, let's see some scenarios:

1. Everything is A-OK: 
true

2. There is an entry on dns about that URL
true/false, depending if their data are equal

3. There is no entry on dns about the URL
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "invalid query"
}

-------------------------------------------------

I've searched for what are valid JSON messagens, and 'true' and 'false' are valid. Or do you want a structure to carry the valid values (scenarios 1 and 2)?

**Comment by igr-santos** [comment]
@luizalbsilva I preferred than this endpoint return a response with the dns hosted flagged and not true or false, because become easy manipular on front-end and is more look like an API Rest
