### ISSUE TITLE
Filter subdomains to remove bonde default entries

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#247]

**Comment by luizalbsilva** [comment]
What am I planning to do:
GET      /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records(.:format)
This will bring data without the default entries

GET      /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records(.:format)?full_data=true
This will bring all data

**Comment by luizalbsilva** [comment]
Branch: feature-issue_247_filter_dns_records

**Comment by luizalbsilva** [comment]
PR #251

**Comment by luizalbsilva** [comment]
On branch develop
