### ISSUE TITLE
Activist's unicity on non-donation actions 

### ISSUE THREAD

**Issue by luizalbsilva** [nossas/bonde-server#263]
we should not let an activist sign twice a form-entry, activist-pressure or activist-match, since there is no reasonable reason to do so.

(In fact, we have a problem today, because mailchimp does not let same email been used twice on the same list or segment -- so you have a number been displayed to the mobilizer from our system, and another from mailchimp)

**Comment by lpirola** [comment]
Phases
1 - Model Validation 
2 - Database Validation

- [ ] Change save order now(donation, then activist), after(activist, then donation)
- [ ] Everywhere we link with activists
- [ ] Whith flows we must change? (donation create?)

**Comment by lpirola** [comment]
https://sentry.io/nossas-cidades/bonde-server/issues/299703816/

**Comment by lpirola** [comment]
Fechando porque estamos implementando validações no próprio bd.
