### ISSUE TITLE
Auto update mailchimp segment with donators separed by recurring and unique

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#278]
doação única paga
doação recorrente ativa

**Comment by luizalbsilva** [comment]
Branch: feature-issue_278-autoupdate_mailchimp_statuses.

On mailchimp, created these merge fields:
   1 - UN_DON (MERGE26)
   2 - REC_DON_AC (MERGE27)

*** Those fields were created on staging list too.**

**Comment by luizalbsilva** [comment]
non-functional requirement change: 
  We will not use fields on mailchimp. Now it's to use 4 segments for each mob:

Main segment:
* M{mob_id){mob_type}{wid_id} - {MOB'S NAME}
Segment for those who paid a donation (single donation)
* M{mob_id){mob_type}{wid_id} - Única Paga - {MOB'S NAME}
Segment for those who paid through the recurrent payments
* M{mob_id){mob_type}{wid_id} - Recorrente Ativa - {MOB'S NAME}
Segment for those who paid through the recurring payments and cancelled
* M{mob_id){mob_type}{wid_id} - Recorrente Inativa - {MOB'S NAME}

**Comment by lpirola** [comment]
Must resync segments to update old donations, only new are synced to mailchimp.

**Comment by lpirola** [comment]
re-synced segments , waiting mailchimp cache to be renewed.
