### ISSUE TITLE
When a mobilization are created with a template the blocks are not copied

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#281]

**Comment by luizalbsilva** [comment]
Adjustment on request payload:

before:  {"template_mobilization_id": xx}
now: {"mobilization" : {"template_mobilization_id": xx}}

Branch: hotfix-issue_281_block_from_template
* _This branch is based on **master**_

**Comment by luizalbsilva** [comment]
There are 2 PR for this issue: 

To Develop: https://github.com/nossas/bonde-server/pull/283
To  release-v0.6.10:  https://github.com/nossas/bonde-server/pull/284
