### ISSUE TITLE
Small checks to custom_domain and slug at mobilization

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#288]
- [x]  Verificar se existe outras mobs com o domínio e tornar o custom_domain único (Adicionar erro na hora de salvar, server side validation)
- [x]  Adicionar opção para editar, aplicar validação e limite de tamanho do slug (63 limite de caracteres, server side validation)
- [x]  Verificar se os slugs que extrapolam o tamanho continuam no ar após atualização dos slugs

**Comment by luizalbsilva** [comment]
There are 5 records which the slug size are greater than 63:

(ID, SLUG, creation date and update date)
 [[174, "130-secretario-queremos-delegacias-da-mulher-24h-e-aos-finais-de-semana-ja", Tue, 07 Jun 2016 14:48:08 BRT -03:00, Tue, 07 Jun 2016 14:48:15 BRT -03:00], [213, "169-para-abrir-os-olhos-melhorando-a-vida-das-moradoras-e-dos-moradores-de-rua", Thu, 04 Aug 2016 10:23:06 BRT -03:00, Wed, 17 Aug 2016 17:55:13 BRT -03:00], [44, "37-pela-memoria-do-menino-eduardo-e-todas-as-vitimas-da-policia-militar-do-rio-de-janeiro", Thu, 05 Nov 2015 11:08:13 BRST -02:00, Tue, 02 May 2017 18:22:46 BRT -03:00], [472, "413-pelo-fim-da-bancada-da-bala-e-pela-volta-do-bombom-serenata-de-amor", Thu, 25 May 2017 12:30:00 BRT -03:00, Fri, 26 May 2017 09:48:54 BRT -03:00], [167, "123-pela-investigacao-dos-casos-de-assedio-moral-e-perseguicao-politica", Wed, 25 May 2016 12:07:09 BRT -03:00, Wed, 25 May 2016 12:30:27 BRT -03:00]]

NONE of them are working in production :(

**Comment by luizalbsilva** [comment]
On PR:  https://github.com/nossas/bonde-server/pull/292

**Comment by igr-santos** [comment]
@luizalbsilva slug should be unique also, today I receive an error with status 422 but without message
