### ISSUE TITLE
Table view to summarize activists stats by mobilization or community

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#298]
- [x] Total Ativistas Únicos
- [x] Total Ativistas Ativos nos últimos 90 dias (novos/recorrentes)

**Comment by gabrielrtakeda** [comment]
Unfortunately the postgraphql still does not have the functionality to make a condition that filters a field as `null` or `not null` as in SQL.. See [this comment](https://github.com/postgraphql/postgraphql/issues/464#issuecomment-301171124) on postgraphql/postgraphql#464

The workaround for lack of this functionality of postgraphql is to create a simple function to filter a field as `null` or `not null`

The aim graphql query is something like the following:

```graphql
query uniqueActivists {
  allDonations (
    condition: {
      // or something that tells to bring only rows that this column is not null
      subscriptionId: !null
    },
    first: 5
  ){
    nodes {
      donationId
      subscriptionId
    }
  }
}
```

**Comment by devton** [comment]
#322
