### ISSUE TITLE
Error when try to filter my templates

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#354]
Na página de criação de novas mobilizações, carregamos os templates globais utilizando a query:

```
{"query":"query allTemplates($communityId: Int!) {
      customTemplates(communityId: $communityId) {
        totalCount
    __typename
  }
  globalTemplates {
        nodes {
          id
      name
      goal
      __typename
    }
    __typename
  }
}
","variables":{"communityId":7},"operationName":"allTemplates"}
```

O comando abaixo executa a query acima em staging:

```curl 'https://data.staging.bonde.org/graphql' -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjozMSwiaWF0IjoxNTAyMjkyOTkxLCJleHAiOjE1MDIzNzkzOTEsImF1ZCI6InBvc3RncmFwaHFsIiwiaXNzIjoicG9zdGdyYXBocWwifQ.ZlLuD9jLJwPIsGNEtzZXLtoa7CaiGg_ur8-sxd4HrwI' -H 'Origin: https://app.staging.bonde.org' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: pt-BR,pt;q=0.8,en-GB;q=0.6,en;q=0.4,en-US;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Referer: https://app.staging.bonde.org/mobilizations/551/templates/choose' -H 'Connection: keep-alive' --data-binary '{"query":"query allTemplates($communityId: Int!) {\n  customTemplates(communityId: $communityId) {\n    totalCount\n    __typename\n  }\n  globalTemplates {\n    nodes {\n      id\n      name\n      goal\n      __typename\n    }\n    __typename\n  }\n}\n","variables":{"communityId":7},"operationName":"allTemplates"}' --compressed```

A query abaixo lista os templates da comunidade:

```
{"query":"query customTemplates($communityId: Int!) {
      customTemplates(communityId: $communityId) {
        nodes {
          id
      name
      goal
      createdAt
      __typename
    }
    __typename
  }
}
","variables":{"communityId":7},"operationName":"customTemplates"}
```

O comando abaixo executa a query acima em staging:

```curl 'https://data.staging.bonde.org/graphql' -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjozMSwiaWF0IjoxNTAyMjkyOTkxLCJleHAiOjE1MDIzNzkzOTEsImF1ZCI6InBvc3RncmFwaHFsIiwiaXNzIjoicG9zdGdyYXBocWwifQ.ZlLuD9jLJwPIsGNEtzZXLtoa7CaiGg_ur8-sxd4HrwI' -H 'Origin: https://app.staging.bonde.org' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: pt-BR,pt;q=0.8,en-GB;q=0.6,en;q=0.4,en-US;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Referer: https://app.staging.bonde.org/mobilizations/551/templates/choose/custom' -H 'Connection: keep-alive' --data-binary '{"query":"query customTemplates($communityId: Int!) {\n  customTemplates(communityId: $communityId) {\n    nodes {\n      id\n      name\n      goal\n      createdAt\n      __typename\n    }\n    __typename\n  }\n}\n","variables":{"communityId":7},"operationName":"customTemplates"}' --compressed```

O problema atualmente é que o resultado dessas queries não são exatamento o que deveria ser, já que está retornando os templates de todas as comunidades.

Tem alguma ideia do que pode ser @igr-santos @devton?

**Comment by igr-santos** [comment]
Isso deve ter haver com o contexto que o @devton comentou outro dia no slack, já estou corrigindo

**Comment by igr-santos** [comment]
Achei necessário adicionar a validação do usuário logado / comunidade
