### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::NumericValueOutOfRange: ERROR:  numeric field overflow

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#416]
https://sentry.io/nossas-cidades/bonde-server/issues/436598821/

```
PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 8, scale 2 must round to an absolute value less than 10^6.

  app/controllers/mobilizations/widgets_controller.rb:23:in `update'
    if @widget.update!(widget_params)
...
(131 additional frame(s) were not displayed)

ActiveRecord::StatementInvalid: PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 8, scale 2 must round to an absolute value less than 10^6.
: UPDATE "widgets" SET "goal" = $1, "settings" = $2, "updated_at" = $3 WHERE "widgets"."id" = $4

ActiveRecord::StatementInvalid: PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 8, scale 2 must round to an absolute value less than 10^6.
: UPDATE "widgets" SET "goal" = $1, "settings" = $2, "updated_at" = $3 WHERE "widgets"."id" = $4
```

**Comment by hudsama** [comment]
@lpirola esse problema aconteceu quando foi dado um update na coluna `goal` em `widgets`
Hoje essa coluna esta como `numeric (524294)`
O que ocorreu foi o estouro dela mesmo. Para evitar isso podemos por um validate no model dos widgets para validar o tamanho dela. 
Algo como:

> `validates_numericality_of :goal, greater_than: 0, less_than: 1000000, allow_nil: true`

Fornecendo o tamanho mínimo e máximo assim como, que essa validação somente ocorrerá quando esse campo estiver preenchido.

**Comment by hudsama** [comment]
[PR] https://github.com/nossas/bonde-server/pull/473
