### ISSUE TITLE
errors related on migrations with permission by roles

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-server#469]
I needed run script following:

```
create role common_user;
create role admin;
create role anonymous;
create role postgraphql;
```

**Comment by lpirola** [comment]
@hudsama seria bom investigar esse bug, junto com a migração das migrations para outro repositório.

**Comment by hudsama** [comment]
@lpirola quando o @igr-santos abriu essa issue eu cheguei a conversar com ele sobre. Um ponto eu já sei aonde atacar. (migrate criando a role `microservices` erroneamente). Mas antes de realizarmos qualquer migração para outro repo estas migrations estarão devidamente corrigidas.
