### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by lucianosousa** [nossas/bonde-server#7]
Will be really nice if someone improve the documentation with what this project do.
New contributors will be thankful. :)

**Comment by lpirola** [comment]
Hi @lucianosousa this repository is used to be a gateway between database and rules business. 

He has endpoints to be accessed by clients, policies to filter what fields can be filled and messages that need to be sent after some action.

We are working in a welcome kit but is still in early stages. We will keep this issue open as a reminder to us and when we finished you will be notified.

**Comment by lucianosousa** [comment]
@lpirola thanks.

I'm waiting here this welcome kit

**Comment by lpirola** [comment]
Hi @lucianosousa, long time no see! :)

We have a better introduction to our project at https://github.com/nossas/bonde-client/blob/master/README.md and we are working with docker, maybe will be easier to setup local development enviroment.

If you found this README not enough, feel free to reopen this issue.
See ya!
