### ISSUE TITLE
Add Gemnasium to track gem vunerabilities

### ISSUE THREAD

**Issue by lucianosousa** [nossas/bonde-server#8]
I suggest you guys add Gemnasium[1] to know when it's the best time to upgrade dependencies

[1] https://gemnasium.com/features

**Comment by lpirola** [comment]
@lucianosousa we just setup https://gemnasium.com/github.com/nossas/bonde-server

If something is needed to update, this must be addressed in #287 

Feel free to reopen

**Comment by lucianosousa** [comment]
🎆
